server:
  port: 8090

spring:
  application:
    name: lab2
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 2003
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
